### ISSUE TITLE
Setting to disable linenumbers for non code languages

### ISSUE THREAD

**Issue by lssch** [q1701/inkdrop-code-block-line-number#10]
It would be nice to have a setting to disable linenumbers for non code languages like mermaid, flowchart etc
![image](https://user-images.githubusercontent.com/37959269/214901977-38a1e2f9-1e15-4e06-b643-35933d12c0e3.png)

**Comment by q1701** [comment]
@lssch Thank you for the report! I will try to fix it.

**Comment by q1701** [comment]
@lssch The issue has been resolved. Kindly try version v0.4.0.

**Comment by lssch** [comment]
Thanks, looks great 👍
