### ISSUE TITLE
Line number disappears on Inkdrop v.5.8.1

### ISSUE THREAD

**Issue by jibundit** [q1701/inkdrop-code-block-line-number#11]
When restarting the inkdrop, the line numbers of the code block disappear. My workaround needs to toggle off and on, but this fix is not permanent.

Inkdrop version: 5.8.1
inkdrop-code-block-line-number: 0.4.0

**Comment by q1701** [comment]
@jibundit 
Thanks.
There is indeed an issue. I will check it, but please give me some time.

**Comment by q1701** [comment]
It appears that this issue occurs when the code-title plugin is used.
My code-block-line-number plugin detects if the code-title plugin is enabled.
As the code-title plugin is actively developed, its specifications might have changed, causing detection issues.
I am continuing to investigate this matter.

**Comment by q1701** [comment]
@jibundit 
I have created a pull request to modify the code-title plugin, and it has been merged by the author, elpnt.
Please try code-title v3.0.1. It should now work alongside code-block-line-number.
Thank you for your report.

**Comment by jibundit** [comment]
@q1701 
It works perfectly. Thank you very much for finding out the root cause.
