### ISSUE TITLE
Make a blank line when combined with code-title

### ISSUE THREAD

**Issue by kputra-xfers** [q1701/inkdrop-code-block-line-number#6]
Hi, there is some possibly bugs. If you use code-block-line-number with [code-title](https://github.com/elpnt/inkdrop-code-title), there will always be a blank line at the very top of the code.

This is when not using title, works perfectly:
<img width="758" alt="Screen Shot 2021-07-29 at 20 16 30" src="https://user-images.githubusercontent.com/86584588/127490342-1b4a24d3-7c06-4069-a123-f75f186f58c6.png">

This is when using title, add a blank line:
<img width="758" alt="Screen Shot 2021-07-29 at 20 16 47" src="https://user-images.githubusercontent.com/86584588/127490428-5c47c99c-dca8-4cdf-ac99-445a264897e7.png">

Thanks 😊

**Comment by q1701** [comment]
@kputra-xfers Thanks for the report ❗   I will investigate incompatibilities with code-title plug-in.

**Comment by q1701** [comment]
@kputra-xfers I have fix it. (v.0.3.0) I hope the problem is solved.

**Comment by kputra-xfers** [comment]
Whoa, sorry I rarely open my github notification.

It works perfectly! 😊

<img width="832" alt="Screen Shot 2021-08-14 at 23 43 10" src="https://user-images.githubusercontent.com/86584588/129451671-ca2a70e6-0caa-4a98-9d90-cf8409502a3c.png">
